import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from "@/components/LenisProvider";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({
  src: [
    {
      path: "../public/fonts/1.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/2.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/3.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/4.woff",
      weight: "400",
      style: "normal",
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body className="overflow-x-hidden">
        <LenisProvider>{children}</LenisProvider>
      </body>
    </html>
  );
}
